// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCygA5CoxXH-JFLAbcJ3ZmBaXLk31_9AhE',
    appId: '1:485350951916:web:422be50ff3d32db818cec9',
    messagingSenderId: '485350951916',
    projectId: 'irtaqi-flutter',
    authDomain: 'irtaqi-flutter.firebaseapp.com',
    storageBucket: 'irtaqi-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP1k225Vnjm2l3JeS-oWAGSru4n4Iw_n0',
    appId: '1:485350951916:android:a4dc548a899ad96818cec9',
    messagingSenderId: '485350951916',
    projectId: 'irtaqi-flutter',
    storageBucket: 'irtaqi-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoXo9ROiiciCtf1cTT2-YYmVY49jFLczw',
    appId: '1:485350951916:ios:0fd90faf2c436bda18cec9',
    messagingSenderId: '485350951916',
    projectId: 'irtaqi-flutter',
    storageBucket: 'irtaqi-flutter.firebasestorage.app',
    iosBundleId: 'com.example.irtaqiNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoXo9ROiiciCtf1cTT2-YYmVY49jFLczw',
    appId: '1:485350951916:ios:0fd90faf2c436bda18cec9',
    messagingSenderId: '485350951916',
    projectId: 'irtaqi-flutter',
    storageBucket: 'irtaqi-flutter.firebasestorage.app',
    iosBundleId: 'com.example.irtaqiNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCygA5CoxXH-JFLAbcJ3ZmBaXLk31_9AhE',
    appId: '1:485350951916:web:422be50ff3d32db818cec9',
    messagingSenderId: '485350951916',
    projectId: 'irtaqi-flutter',
    authDomain: 'irtaqi-flutter.firebaseapp.com',
    storageBucket: 'irtaqi-flutter.firebasestorage.app',
  );

}